/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LayoutRouteImport } from "./routes/_layout";
import { Route as LoginIndexRouteImport } from "./routes/login/index";
import { Route as LayoutIndexRouteImport } from "./routes/_layout/index";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as LayoutManagerSkillNewRouteImport } from "./routes/_layout/manager/skill/new";

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutManagerSkillNewRoute = LayoutManagerSkillNewRouteImport.update({
  id: "/manager/skill/new",
  path: "/manager/skill/new",
  getParentRoute: () => LayoutRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRoute;
  "/login/": typeof LoginIndexRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/manager/skill/new": typeof LayoutManagerSkillNewRoute;
}
export interface FileRoutesByTo {
  "/": typeof LayoutIndexRoute;
  "/login": typeof LoginIndexRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/manager/skill/new": typeof LayoutManagerSkillNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_layout": typeof LayoutRouteWithChildren;
  "/_layout/": typeof LayoutIndexRoute;
  "/login/": typeof LoginIndexRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/_layout/manager/skill/new": typeof LayoutManagerSkillNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login/" | "/api/rpc/$" | "/manager/skill/new";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/api/rpc/$" | "/manager/skill/new";
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/"
    | "/login/"
    | "/api/rpc/$"
    | "/_layout/manager/skill/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren;
  LoginIndexRoute: typeof LoginIndexRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login/";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_layout/": {
      id: "/_layout/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof LayoutIndexRouteImport;
      parentRoute: typeof LayoutRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_layout/manager/skill/new": {
      id: "/_layout/manager/skill/new";
      path: "/manager/skill/new";
      fullPath: "/manager/skill/new";
      preLoaderRoute: typeof LayoutManagerSkillNewRouteImport;
      parentRoute: typeof LayoutRoute;
    };
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute;
  LayoutManagerSkillNewRoute: typeof LayoutManagerSkillNewRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutManagerSkillNewRoute: LayoutManagerSkillNewRoute,
};

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
