name: 🔎 Code Quality

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linter:
    name: 🧹 Linter
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Run linter
        run: bun run lint:oxlint

  typescriptChecker:
    name: 🟦 TypeScript Checker
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Run TypeScript checker
        run: bun run lint:ts

  tests:
    name: 🔬 Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Run tests
        run: SKIP_ENV_VALIDATION=true bun run test:ci
